### ISSUE TITLE
Open API, crawling 데이터 가져오기 

### ISSUE THREAD

**Issue by subsub97** [valueGa/valueGa_backend#3]
## 💡 Feature Issue

이슈 설명
각 주식 종목에 해당하는 데이터 오픈 API,크롤링으로 가져오기 (PER 테플릿 전용)

### 데이터 가져오기
  - [x]  기간
  - [x] 매출액
  - [ ] 매출원가
  - [x] 매출총이익
  - [x] 판관비
  - [x] 영업이익
  - [x] 금융수익
  - [x] 금융비용
  - [x] 금융손익
  - [x] 기타이익
  - [x] 기타손실
  - [x] 기타손익
  - [ ] 세전당기순이익 (법인세비용차감전수이익)
  - [x] 세금 (법인세비용(수익))
  - [x] 당기순이익
  - [x] 발행주식총수
  - [x] 유통주식
  - [x] ROE
  - [x] EPS
  - [x] BPS
  - [x] EV/EBITDA
  - [x] 부채비율
  - [x] 유보비율

**Comment by Phoebe125** [comment]
LGTM :)
